### ISSUE TITLE
verify new IERC20 on blockscout

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/predeploy-contracts#171]
currently predeployed erc20 on blockscout are verified with old ERC20 interface (i.e. no `transferToAccount32`), so blockscout can't decode some of it's data

for example: https://blockscout.acala.network/tx/0x5c5d5a660743599e542fe2ea7aea1507d6ccb28de120a4a46a9d656944ef9276/logs
<img width="559" alt="Screenshot 2024-02-02 at 10 48 12" src="https://github.com/AcalaNetwork/predeploy-contracts/assets/16548786/8e202f4c-51ce-4572-a70f-1aa619d3d9c5">

**Comment by zjb0807** [comment]
updated

**Comment by zjb0807** [comment]
updated on karura and acala
