### ISSUE TITLE
Wrong  RENBTC contract address 

### ISSUE THREAD

**Issue by angdiam** [AcalaNetwork/predeploy-contracts#63]
In Readme RENBTC contract address: 0x0000000000000000000000000000000001000004
In bytecodes.json and tokens.json 
"RENBTC",
 "0x0000000000000000000000000000000001000014",

For me the Readme address is working fine and I corrected bytecodes.json and tokens.json  accordingly

**Comment by zjb0807** [comment]
`bytecodes.json` and `tokens.json` are the latest, maybe the readme is not updated. 
If it doesn't work for you, maybe you are using an older node.
The address is now updated. I will update the readme. Please use the v2.0.1 node
