### ISSUE TITLE
Issues when $ yarn run generate-bytecode

### ISSUE THREAD

**Issue by angdiam** [AcalaNetwork/predeploy-contracts#64]
Readme says
"To generate bytecode, run yarn run generate-bytecode."
I have the following errors (this is downloading and running the repo after yarn install)

$ yarn run generate-bytecode
yarn run v1.22.10
$ node generate/generate.js
>>> generating contracts bytecode failed:  Error: Command failed: tsc contracts/utils/Address.js --declaration --allowJs --emitDeclarationOnly
/bin/sh: tsc: command not found

    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'tsc contracts/utils/Address.js --declaration --allowJs --emitDeclarationOnly',
  stdout: '',
  stderr: '/bin/sh: tsc: command not found\n'
}
✨  Done in 12.65s.

**Comment by xlc** [comment]
we need to add typescript to dev dependency

**Comment by ThunderDeliverer** [comment]
@angdiam we added the fix for your issue. Please let us know it the issue persists.

To use it, update your local clone to the latest version and run `yarn` again to install the new dependency.
